#!/bin/bash

FROM golang:alpine

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY . .

RUN go mod tidy

RUN go build -o binary

ENTRYPOINT ["/app/binary"]

 docker tag devcode-repov2:latest azilkhaq/devcode-repov2:latest   
 docker push azilkhaq/devcode-repov2:latest   